# Generated by Django 3.2.9 on 2021-11-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0002_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ImageField(null=True, upload_to='blogs'),
        ),
    ]
